repos:
-   repo: local
    hooks:
    -   id: format
        name: format
        entry: make format
        pass_filenames: false
        language: system
        stages: [commit]
    -   id: test
        name: test
        entry: make test
        pass_filenames: false
        language: system
        stages: [commit]
    -   id: check
        name: check
        entry: make check
        pass_filenames: false
        language: system
        stages: [commit]


-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        stages: [commit]
    -   id: detect-private-key
        stages: [commit]
    -   id: check-merge-conflict
        stages: [commit]
 
-   repo: https://github.com/lumapps/commit-message-validator
    rev: 1.1.0
    hooks:
      - id: commit-message-validator
        stages: [commit-msg]
        args: [--allow-temp, --no-jira]